ALTER TABLE preguntas
  ADD COLUMN IF NOT EXISTS opcion_a_imagen_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS opcion_b_imagen_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS opcion_c_imagen_url TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS opcion_d_imagen_url TEXT DEFAULT NULL;
